import { BaseUserResDto } from 'src/core/users/dto/res/user.dto'
import { USER_ROLE } from 'src/core/users/types/user-role.enum'

export const MOCK_USERS: Record<USER_ROLE, BaseUserResDto> = {
  [USER_ROLE.COMPANY]: {
    id: 1,
    username: 'chu2409',
    password: '123456',
    dni: '0707047643',
    email: 'dzhu2409@gmail.com',
    name: 'Daniel',
    surname: 'Zhu',
    role: USER_ROLE.COMPANY,
    isActive: true,
    companyId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  [USER_ROLE.CLERK]: {
    id: 2,
    username: 'pepito12',
    password: '123456',
    dni: '0700941503',
    email: 'pepito12@gmail.com',
    name: 'Pepito',
    surname: 'Pérez',
    role: USER_ROLE.CLERK,
    isActive: true,
    companyId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  [USER_ROLE.DRIVER]: {
    id: 3,
    username: 'juanito34',
    password: '123456',
    dni: '0703224345',
    email: 'juanito34@gmail.com',
    name: 'Juanito',
    surname: 'Gómez',
    role: USER_ROLE.DRIVER,
    isActive: true,
    companyId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  [USER_ROLE.CUSTOMER]: {
    id: 4,
    username: 'maria23',
    password: '123456',
    dni: '0703224337',
    email: 'maria23@gmail.com',
    name: 'María',
    surname: 'López',
    role: USER_ROLE.CUSTOMER,
    isActive: true,
    companyId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  [USER_ROLE.ADMIN]: {
    id: 5,
    username: 'admin',
    password: '123456',
    dni: '0703224317',
    email: 'admin@gmail.com',
    name: 'Admin',
    surname: 'Admin',
    role: USER_ROLE.ADMIN,
    isActive: true,
    companyId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
}
