version: '3.8'

services:
  api:
    container_name: ecuatickets-api-local
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=development
    restart: unless-stopped
